package component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import main.Main;
import net.miginfocom.swing.MigLayout;
import swing.WrapLayout;

public class Panel_More extends javax.swing.JPanel {

    private JPanel panelHeader;

    private JPanel panelDetail;

    public Panel_More() {
        initComponents();
        init();
    }

    public void init() {
        setLayout(new MigLayout("fillx"));

        panelHeader = new JPanel();
        panelHeader.setLayout(new BoxLayout(panelHeader, BoxLayout.LINE_AXIS));
        panelHeader.add(getButtonFile());
        panelHeader.add(getButtonEmojiStyleAnimal());
        panelHeader.add(getButtonEmojiStyleFood());
        panelHeader.add(getButtonEmojiStylePeople());
        panelHeader.add(getButtonEmojiStyleSmiley());
        add(panelHeader, "w 100%, h 45!, wrap");
        panelDetail = new JPanel();
        JScrollPane sp = new JScrollPane(panelDetail);
        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sp.setVerticalScrollBar(new JScrollBar());

        add(sp, "w 100%, h 100%");
    }

    private JButton getButtonFile() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/icon/link.png")));
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.showOpenDialog(Main.getFrames()[0]);
                // Phần này là để gửi file, sẽ update sau
            }
        });
        return cmd;
    }

    private JButton getButtonEmojiStyleAnimal() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/emoji/emoji animal/icons8-cat-face-50.png")));
//        cmd.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                JFileChooser fileChooser = new JFileChooser();
//                fileChooser.showOpenDialog(Main.getFrames()[0]);
//                // Phần này là để gửi file, sẽ update sau
//            }
//        });
        return cmd;
    }
    private JButton getButtonEmojiStyleFood() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/emoji/emoji food & drink/icons8-bubble-tea-50.png")));
//        cmd.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                JFileChooser fileChooser = new JFileChooser();
//                fileChooser.showOpenDialog(Main.getFrames()[0]);
//                // Phần này là để gửi file, sẽ update sau
//            }
//        });
        return cmd;
    }
    private JButton getButtonEmojiStylePeople() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/emoji/emoji people & body/icons8-heart-hands-50.png")));
//        cmd.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                JFileChooser fileChooser = new JFileChooser();
//                fileChooser.showOpenDialog(Main.getFrames()[0]);
//                // Phần này là để gửi file, sẽ update sau
//            }
//        });
        return cmd;
    }
    private JButton getButtonEmojiStyleSmiley() {
        OptionButton cmd = new OptionButton();
        cmd.setIcon(new ImageIcon(getClass().getResource("/emoji/emoji smileys & emoiton/icons8-face-holding-back-tears-50.png")));
//        cmd.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                JFileChooser fileChooser = new JFileChooser();
//                fileChooser.showOpenDialog(Main.getFrames()[0]);
//                // Phần này là để gửi file, sẽ update sau
//            }
//        });
        return cmd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
